spring:
  # 视图解析器
  thymeleaf:
    encoding: utf-8
    suffix: .html
    prefix: classpath:/templates/
    mode: HTML
    cache: false
    servlet:
      content-type: text/html
  mvc:
    static-path-pattern: /static/**
  # 配置数据源
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    # serverTimezone=UTC 世界统一时间  GMT格林尼治所在地标准时间 CTT（Asia&Shanghai）亚洲时间
    url: jdbc:mysql://localhost:3306/erp?useSSL=false&serverTimezone=CTT
    username: root
    password: root

  # 日期类型转换
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

  servlet:
    multipart:
      enabled: true
      max-file-size: 20MB
      max-request-size: 20MB

# 日志
logging:
  file:
    name: log/erpLog.log

# mybatis 配置
mybatis:
  # mapper.xml文件所在
  mapper-locations: classpath:mapper/*/*.xml
  # 实体类所在包
  type-aliases-package: com.xt.entity
  configuration:
    # 打印数据库语句 用于测试
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#静态资源路径配置
#spring.mvc.static-path-pattern=/static/**

